# Permalinks
permalink:        pretty

# Setup
title:            Eric Crosson
tagline:          Zen in the Art of Emacs
url:              http://ericcrosson.com
paginate:         1
baseurl:          /
author:
  name:           Eric Crosson
  url:            https://github.com/EricCrosson
  email:          esc@ericcrosson.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/EricCrosson/ericcrosson.github.io
